[package]
name = "qcow2-fuse"
version = "0.1.0"
authors = ["Dave Vasilevsky <dave@vasilevsky.ca>"]

[dependencies]
fuse = "0.2"
time = "0.1.35"
libc = "0.2.13"
log = "0.3"
daemonize = "0.2.2"
positioned-io = "0.2.0"
qcow2 = "0.1.0"
